$ptf_path="C:\Program Files\PeopleSoft\PeopleSoft Test Framework"
$server="myserver:9300"
$node="PT_LOCAL"
$user="PS"
$pass="PS"
$exeopt="PSFTDB_Verbose"
$tests += ,@("MY_TEST", "DEFAULT","TEST")
$tests += ,@("MY_TEST_NEW", "DEFAULT","TEST")
$tests += ,@("MY_TEST_NEW1", "DEFAULT","TEST")
